# Generated by Django 5.0.7 on 2024-12-01 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('diary_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('text', models.TextField(max_length=300)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries_by_user', to='domain.user')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries_by_username', to='domain.user')),
            ],
        ),
    ]
