# Generated by Django 5.0.7 on 2024-12-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='user_id',
            new_name='user',
        ),
    ]
