# Generated by Django 5.0.7 on 2024-10-23 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
        ('intshop', '0003_product_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=120)),
                ('book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intshop.product_book')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intshop.category_product')),
                ('movie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intshop.product_movie')),
                ('music_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intshop.product_music')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.user')),
            ],
        ),
    ]
