# Generated by Django 5.1.1 on 2024-09-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120)),
                ('password', models.TextField()),
                ('user_email', models.CharField(max_length=120)),
            ],
        ),
    ]
